name: Deploy Laravel to Production

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: lamedy/rpg-finder
  IMAGE_TAG: latest

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG

      - name: Deploy to production via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker run -d \
            --name rpg-finder-container \
            --network appnet \
            -p 80:80 \
            -e DB_HOST=62.60.217.31 \
            -e DB_PORT=3306 \
            -e DB_DATABASE=diplom_db \
            -e DB_USERNAME=kajos \
            -e DB_PASSWORD=4004 \
            lamedy/rpg-finder:latest
